server:
  port: 8080
  servlet:
    context-path: /jzl
  ssl:
    key-store: classpath:server.keystore
    key-alias: tomcat
    enabled: true
    key-store-password: 123456
    key-store-type: jks
spring:
  datasource:
    url: jdbc:mysql://10.121.198.68:3306/jzl?useUnicode=true&amp;characterEncoding=utf-8&amp;useSSL=false
    username: root
    password: passwd
    driver-class-name: com.mysql.jdbc.Driver
mybatis-plus:
  mapper-locations: classpath*:mybatis/*.xml
  type-aliases-package: com.jzl.entity
  global-config:
    db-config:
      id-type: auto
      field-strategy: ignored
      table-underline: true
  configuration:
    map-underscore-to-camel-case: true
#java -cp jasypt-1.9.2.jar org.jasypt.intf.cli.JasyptPBEStringEncryptionCLI input="ceshi" password=jzl algorithm=PBEWithMD5AndDES
#jzl: ENC(jl2ZmYPIVvxlTLkHRkMKrQ==)
jzl: ceshi
jasypt:
  encryptor:
    password: jzl
