server:
  port: 8080
  servlet:
    context-path: /jzl
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/jzl?useUnicode=true&amp;characterEncoding=utf-8&amp;useSSL=false
    data-username: root
    data-password: passwd
    driver-class-name: com.mysql.jdbc.Driver